GO
CREATE TYPE [DBO].[NAME] FROM NVARCHAR(50)
GO
CREATE TYPE [DBO].[ID] FROM CHAR(10)
GO
CREATE TABLE [NHANVIEN]
(
    [MANV] [ID] NOT NULL,
    [CHUCVU] [VARCHAR](30) NOT NULL,
    [PHONGBAN] [ID],
    [NGAYVAOLAM] [DATETIME],
    [NGAYNGHILAM] [DATETIME],
    [NGUOIQL] [ID],
)
ALTER TABLE [NHANVIEN]
    ADD CONSTRAINT PK_NHANVIEN
        PRIMARY KEY ([MANV])
ALTER TABLE [NHANVIEN]
    ADD CONSTRAINT FK_NHANVIEN_PHONGBAN
        FOREIGN KEY ([PHONGBAN]) REFERENCES [DBO].[PHONGBAN]([MAPB]);
ALTER TABLE [NHANVIEN]
    ADD CONSTRAINT FK_NHANVIEN_NGUOIQL
        FOREIGN KEY ([NGUOIQL]) REFERENCES [DBO].[NHANVIEN]([MANV]);
CREATE TABLE MAIL
(
    [MANV] [ID] NOT NULL,
    [MESSAGE] NVARCHAR(1000),
    [NGUOIGUI] [ID] NOT NULL
)
CREATE TABLE [TT_CANHAN]
(
    [MANV] [ID] NOT NULL,
    [HOTEN] [NAME] NOT NULL,
    [NAMSINH] [DATETIME],
    [QUEQUAN] [NAME],
    [SODT] [CHAR](20),
    [TRINGDOHOCVAN] [NAME],
    [CHUYENNGANH] [NAME],
    [DIACHI] [NAME],
    [EMAIL] [NAME],
    [SOCMND] [CHAR](20),
)
ALTER TABLE [TT_CANHAN]
    ADD CONSTRAINT PK_TT_CANHAN
        PRIMARY KEY ([MANV]);
ALTER TABLE [TT_CANHAN]
    ADD CONSTRAINT FK_TTCANHAN_NHANVIEN
        FOREIGN KEY ([MANV]) REFERENCES [DBO].[NHANVIEN]([MANV]);
CREATE TABLE [NGUOITHAN]
(
    [MANV] [ID] NOT NULL,
    [TEN] [NAME],
    [NAMSINH] [DATETIME],
    [QUANHE] [NAME],
    [SODIENTHOAI] CHAR(20) NOT NULL
)
ALTER TABLE [NGUOITHAN]
    ADD CONSTRAINT PK_NGUOITHAN
        PRIMARY KEY ([MANV], [SODIENTHOAI]);
ALTER TABLE [NGUOITHAN]
    ADD CONSTRAINT FK_NGUOITHAN_NHANVIEN
        FOREIGN KEY ([MANV]) REFERENCES [DBO].[NHANVIEN]([MANV]);
CREATE TABLE [PHUCLOI]
(
    [MAPHUCLOI] [ID] NOT NULL,
    [TENPHUCLOI] [NAME],
    [LUONGCONGTHEM] [INT],
    [NGAYHIEULUC] [DATETIME],
    [NGAYKETTHUC] [DATETIME],
    [COMMENT] [VARCHAR](150),
)
ALTER TABLE [PHUCLOI]
    ADD CONSTRAINT PK_PHUCLOI
        PRIMARY KEY ([MAPHUCLOI]);

CREATE TABLE [NHANVIENPHUCLOI]
(
    [MANV] [ID] FOREIGN KEY REFERENCES [DBO].[NHANVIEN]([MANV]),
    [MAPHUCLOI] [ID] FOREIGN KEY REFERENCES [DBO].[PHUCLOI]([MAPHUCLOI]),
)
CREATE TABLE [LUONG]
(
    [MALUONG] [ID] NOT NULL,
    [MANV] [ID] NOT NULL,
    [MUCLUONG] [FLOAT],
    [NGAYBATDAU] [DATETIME],
    [NGAYKETTHUC] [DATETIME],
    [THUCLANH] [MONEY], --(MUCLUONG - SONGAYNGHI*HESOPHAT)+ PHUC LOI
    CONSTRAINT [PK_MALUONG] PRIMARY KEY CLUSTERED
        (
         [MALUONG] ASC
            )
)
ALTER TABLE [LUONG]
    ADD CONSTRAINT FK_LUONG_NHANVIEN
        FOREIGN KEY ([MANV]) REFERENCES [DBO].[NHANVIEN]([MANV]);
CREATE TABLE [NGAYNGHI]
(
    [MANV] [ID],
    [NGAYNGHI] [DATETIME],
)
ALTER TABLE [NGAYNGHI]
    ADD CONSTRAINT FK_NGAYNGHI_NHANVIEN
        FOREIGN KEY ([MANV]) REFERENCES [DBO].[NHANVIEN]([MANV]);
CREATE TABLE [TAIKHOAN]
(
    [MATK] [ID] NOT NULL,
    [MATKHAU] [CHAR](20) NOT NULL,
    [LOAITK] [ID],
)
ALTER TABLE [TAIKHOAN]
    ADD CONSTRAINT PK_TAIKHOAN
        PRIMARY KEY ([MATK], [MATKHAU]);
ALTER TABLE [TAIKHOAN]
    ADD CONSTRAINT FK_TAIKHOAN_NHANVIEN
        FOREIGN KEY ([MATK]) REFERENCES [DBO].[NHANVIEN]([MANV]);
CREATE TABLE [PHONGBAN]
(
    [MAPB] [ID] NOT NULL,
    [TENPB] [NAME] NOT NULL,
    [TRUONGPB] [ID] NOT NULL,
)
ALTER TABLE [PHONGBAN]
    ADD CONSTRAINT PK_PHONGBAN
        PRIMARY KEY ([MAPB]);
ALTER TABLE [PHONGBAN]
    ADD CONSTRAINT FK_PHONGBAN_NHANVIEN
        FOREIGN KEY ([TRUONGPB]) REFERENCES [DBO].[NHANVIEN]([MANV]);
